import { Pegawai, RiwayatSK, KeluargaKP4, AuditLog, UnitKerjaItem, UserAccount, AplikasiKepegawaian } from '../types';

export const INITIAL_PEGAWAI: Pegawai[] = [
  {
    nip: '197108071992031007',
    nik: '1971080719920310',
    nama_lengkap: 'MUHSAN',
    gelar_depan: '',
    gelar_belakang: '',
    tempat_lahir: 'Lombok Timur',
    tanggal_lahir: '1971-08-07',
    jenis_kelamin: 'L',
    status_kepegawaian: 'PNS',
    profesi_sdmk: 'Analis Penerimaan Keuangan',
    jenis_jabatan: 'Pelaksana',
    jabatan_spesifik: 'Analis Penerimaan Keuangan',
    unit_kerja: 'SEKRETARIAT',
    status_ukom: false,
    tmt_cpns: '1992-03-01',
    pendidikan_terakhir: 'S1 ',
    status_izin_belajar: false,
    no_whatsapp: '',
    sisa_cuti_tahunan: 6,
    is_deleted: false,
    created_at: '2026-08-24T14:23:50.592+00:00',
    updated_at: undefined,
    jenjang_jabatan: 'Ahli Pertama',
    ak_konversi_skp: 12.5,
    total_ak_kumulatif: 37.5,
    predikat_skp_terakhir: 'Baik',
    status_ukkj: 'Tidak ada',
    no_sertifikat_ukkj: '',
    tgl_lulus_ukkj: '',
    status_ujian_dinas: 'Tidak ada',
    no_stlud: '',
    status_pencantuman_gelar: 'Tidak ada',
    nama_universitas_pt: '',
    program_studi: 'Ilmu Administrasi Negara',
    progres_semester: undefined,
    akreditasi_pt: undefined,
    tmt_kgb_terakhir: '2026-08-25',
    tmt_pangkat_terakhir: '2026-08-25',
    golongan_pangkat: 'III/c',
    nama_pangkat: 'Penata',
    tmt_golongan: '2023-10-01',
    masa_kerja_tahun: 23,
    masa_kerja_bulan: 0,
    no_sk_pangkat: 'SK III/c',
    tgl_sk_pangkat: '2023-10-01',
    jenis_mutasi: 'Kenaikan Pangkat Reguler',
    no_pertek_bkn: '',
    tgl_pertek_bkn: '',
    nama_jabatan_pns: undefined,
    tmt_jabatan_pns: undefined,
    no_sk_jabatan_pns: undefined,
    ni_pppk: '',
    no_perjanjian_kerja: '',
    tgl_perjanjian_kerja: '',
    tmt_perjanjian_mulai: '',
    tmt_perjanjian_selesai: '',
    golongan_pppk: 'Golongan IX',
    no_sk_pppk: '',
    satker: 'SEKRETARIAT',
    no_sk_kontrak: '',
    masa_kerja_non_asn: '1 Tahun',
    sumber_pembiayaan: 'BLUD',
  },
  {
    nip: '197604202010012006',
    nik: '1976042020100120',
    nama_lengkap: 'NINING ARIANTI',
    gelar_depan: '',
    gelar_belakang: 'SE',
    tempat_lahir: 'Lombok Timur',
    tanggal_lahir: '1976-04-20',
    jenis_kelamin: 'P',
    status_kepegawaian: 'PNS',
    profesi_sdmk: 'Kepala Sub Bagian Keuangan ',
    jenis_jabatan: 'Struktural',
    jabatan_spesifik: 'Kasubag Keuangan',
    unit_kerja: 'SEKRETARIAT',
    status_ukom: false,
    tmt_cpns: '2010-01-01',
    pendidikan_terakhir: 'S1',
    status_izin_belajar: false,
    no_whatsapp: '',
    sisa_cuti_tahunan: 12,
    is_deleted: false,
    created_at: '2026-08-25T14:00:02.042+00:00',
    updated_at: undefined,
    jenjang_jabatan: 'Eselon IV.a',
    ak_konversi_skp: 12.5,
    total_ak_kumulatif: 37.5,
    predikat_skp_terakhir: 'Baik',
    status_ukkj: 'Belum UKKJ',
    no_sertifikat_ukkj: '',
    tgl_lulus_ukkj: '',
    status_ujian_dinas: 'Tidak ada',
    no_stlud: '',
    status_pencantuman_gelar: 'Tidak ada',
    nama_universitas_pt: '',
    program_studi: 'Ekonomi',
    progres_semester: undefined,
    akreditasi_pt: undefined,
    tmt_kgb_terakhir: undefined,
    tmt_pangkat_terakhir: undefined,
    golongan_pangkat: 'III/b',
    nama_pangkat: 'Penata Muda Tingkat I',
    tmt_golongan: '2021-10-21',
    masa_kerja_tahun: 0,
    masa_kerja_bulan: 0,
    no_sk_pangkat: 'SK 3b',
    tgl_sk_pangkat: '2021-10-21',
    jenis_mutasi: 'Kenaikan Pangkat Reguler',
    no_pertek_bkn: '',
    tgl_pertek_bkn: '',
    nama_jabatan_pns: undefined,
    tmt_jabatan_pns: undefined,
    no_sk_jabatan_pns: undefined,
    ni_pppk: '',
    no_perjanjian_kerja: '',
    tgl_perjanjian_kerja: '',
    tmt_perjanjian_mulai: '',
    tmt_perjanjian_selesai: '',
    golongan_pppk: 'Golongan IX',
    no_sk_pppk: '',
    satker: 'SEKRETARIAT',
    no_sk_kontrak: '',
    masa_kerja_non_asn: '1 Tahun',
    sumber_pembiayaan: 'BLUD',
  },
];

export const INITIAL_SK_HISTORY: RiwayatSK[] = [];

export const INITIAL_KELUARGA: KeluargaKP4[] = [
  {
    id: 'kp4-1787702044310',
    nip_pegawai: '197108071992031007',
    nama_keluarga: 'dfgfdgd',
    status_hubungan: 'Anak',
    tanggal_lahir: '2000-01-13',
    status_tanggungan: true,
    pekerjaan: '',
    nama_sekolah_pt: '',
    surat_ket_kuliah_url: null,
    no_surat_kuliah: '',
    tgl_surat_kuliah: '2026-08-25',
    semester_kuliah: null,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1787709130290-813',
    admin_email: 'dinkes@gmail.com',
    aksi: 'Update',
    tabel_terdampak: 'pegawai',
    deskripsi: 'Memperbarui biodata pegawai NIP 197108071992031007 (MUHSAN)',
    created_at: '2026-08-26T01:52:10.29+00:00',
  },
  {
    id: 'log-init-001',
    admin_email: 'admin.dikes@lombokbaratkab.go.id',
    aksi: 'System Initialize',
    tabel_terdampak: 'master_database',
    deskripsi: 'Sistem SIMORANG DINKES-PPKB Lombok Barat siap digunakan untuk perekaman data real kepegawaian.',
    created_at: '2026-08-25T13:10:35.943+00:00',
  },
];

export const INITIAL_UNITS: UnitKerjaItem[] = [
  {
    id: 'unit-1787625153568',
    kode_unit: '01',
    nama_unit: 'SEKRETARIAT',
    kategori: 'Dinas',
    alamat: 'Jl. Ahmad Yani No. 1 Gerung, Lombok Barat',
    telepon: '(0370) 681345',
    kepala_unit: 'Drs. H. Fathurrahman, M.Si',
    nip_kepala: '197001011995031002',
    status: 'Aktif',
  },
  {
    id: 'unit-002',
    kode_unit: '02',
    nama_unit: 'BIDANG KESEHATAN MASYARAKAT (KESMAS)',
    kategori: 'Dinas',
    alamat: 'Dinas Kesehatan Kab. Lombok Barat',
    telepon: '',
    kepala_unit: '',
    nip_kepala: '',
    status: 'Aktif',
  },
  {
    id: 'unit-003',
    kode_unit: '03',
    nama_unit: 'BIDANG PENCEGAHAN & PENGENDALIAN PENYAKIT (P2P)',
    kategori: 'Dinas',
    alamat: 'Dinas Kesehatan Kab. Lombok Barat',
    telepon: '',
    kepala_unit: '',
    nip_kepala: '',
    status: 'Aktif',
  },
  {
    id: 'unit-004',
    kode_unit: '04',
    nama_unit: 'BIDANG PELAYANAN KESEHATAN (YANKES)',
    kategori: 'Dinas',
    alamat: 'Dinas Kesehatan Kab. Lombok Barat',
    telepon: '',
    kepala_unit: '',
    nip_kepala: '',
    status: 'Aktif',
  },
  {
    id: 'unit-005',
    kode_unit: '05',
    nama_unit: 'BIDANG SUMBER DAYA KESEHATAN (SDK)',
    kategori: 'Dinas',
    alamat: 'Dinas Kesehatan Kab. Lombok Barat',
    telepon: '',
    kepala_unit: '',
    nip_kepala: '',
    status: 'Aktif',
  },
];

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'usr-001',
    username: 'yudi',
    nama_lengkap: 'Administrator DINKES-PPKB (Admin Utama)',
    email: 'admin.dikes@lombokbaratkab.go.id',
    role: 'Admin Dinkes',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    nip: '198001012005011001',
    no_hp: '081234567890',
    status: 'Aktif',
    terakhir_login: '2026-08-26 15:53',
    created_at: '2026-01-01T00:00:00+00:00',
    password: 'admin',
  },
  {
    id: 'usr-1787564041162',
    username: 'duta',
    nama_lengkap: 'Faturrahman',
    email: 'dinkes@gmail.com',
    password: 'admin',
    role: 'Admin Dinkes',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    nip: undefined,
    no_hp: undefined,
    status: 'Aktif',
    terakhir_login: '2026-08-26 15:42',
    created_at: '2026-08-24T09:34:01.162+00:00',
  },
];

export const INITIAL_APLIKASI_KEPEGAWAIAN: AplikasiKepegawaian[] = [];
