import { Pegawai, RiwayatSK, KeluargaKP4, AuditLog, UnitKerjaItem, UserAccount, AplikasiKepegawaian } from '../types';

// DATA MASTER REAL (KOSONG AWAL UNTUK PENGISIAN DATA REAL KEPEGAWAIAN DARI DATABASE)
export const INITIAL_PEGAWAI: Pegawai[] = [];

export const INITIAL_SK_HISTORY: RiwayatSK[] = [];

export const INITIAL_KELUARGA: KeluargaKP4[] = [];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-init-001',
    admin_email: 'admin.dikes@lombokbaratkab.go.id',
    aksi: 'System Initialize',
    tabel_terdampak: 'master_database',
    deskripsi: 'Sistem SIMORANG DINKES-PPKB Lombok Barat siap digunakan untuk perekaman data real kepegawaian.',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_UNITS: UnitKerjaItem[] = [
  {
    id: 'unit-001',
    kode_unit: 'DINAS-01',
    nama_unit: 'Dinas Kesehatan Kab. Lombok Barat',
    kategori: 'Dinas',
    alamat: 'Jl. Soekarno-Hatta No. 1, Gerung',
    telepon: '(0370) 681234',
    kepala_unit: 'Kepala Dinas Kesehatan',
    status: 'Aktif',
  },
  {
    id: 'unit-002',
    kode_unit: 'PKM-01',
    nama_unit: 'Puskesmas Gerung',
    kategori: 'Puskesmas',
    alamat: 'Jl. Gatot Subroto, Gerung',
    telepon: '(0370) 682334',
    kepala_unit: 'Kepala Puskesmas Gerung',
    status: 'Aktif',
  },
  {
    id: 'unit-003',
    kode_unit: 'PKM-02',
    nama_unit: 'Puskesmas Narmada',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Narmada, Kec. Narmada',
    telepon: '(0370) 671112',
    kepala_unit: 'Kepala Puskesmas Narmada',
    status: 'Aktif',
  },
  {
    id: 'unit-004',
    kode_unit: 'PKM-03',
    nama_unit: 'Puskesmas Meninting',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Senggigi, Batu Layar',
    telepon: '(0370) 692223',
    kepala_unit: 'Kepala Puskesmas Meninting',
    status: 'Aktif',
  },
  {
    id: 'unit-005',
    kode_unit: 'PKM-04',
    nama_unit: 'Puskesmas Labuapi',
    kategori: 'Puskesmas',
    alamat: 'Jl. TGH. Lopan, Labuapi',
    telepon: '(0370) 672556',
    kepala_unit: 'Kepala Puskesmas Labuapi',
    status: 'Aktif',
  },
  {
    id: 'unit-006',
    kode_unit: 'PKM-05',
    nama_unit: 'Puskesmas Gunungsari',
    kategori: 'Puskesmas',
    alamat: 'Jl. Pariwisata Gunungsari',
    telepon: '(0370) 673441',
    kepala_unit: 'Kepala Puskesmas Gunungsari',
    status: 'Aktif',
  },
  {
    id: 'unit-007',
    kode_unit: 'PKM-06',
    nama_unit: 'Puskesmas Sekotong',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Sekotong, Sekotong Barat',
    telepon: '(0370) 683445',
    kepala_unit: 'Kepala Puskesmas Sekotong',
    status: 'Aktif',
  },
  {
    id: 'unit-008',
    kode_unit: 'PKM-07',
    nama_unit: 'Puskesmas Kediri',
    kategori: 'Puskesmas',
    alamat: 'Jl. TGH. Abdul Karim, Kediri',
    telepon: '(0370) 671882',
    kepala_unit: 'Kepala Puskesmas Kediri',
    status: 'Aktif',
  },
  {
    id: 'unit-009',
    kode_unit: 'PKM-08',
    nama_unit: 'Puskesmas Lingsar',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Lingsar, Kec. Lingsar',
    telepon: '(0370) 672110',
    kepala_unit: 'Kepala Puskesmas Lingsar',
    status: 'Aktif',
  },
  {
    id: 'unit-010',
    kode_unit: 'PKM-09',
    nama_unit: 'Puskesmas Suranadi',
    kategori: 'Puskesmas',
    alamat: 'Jl. Wisata Suranadi, Narmada',
    telepon: '(0370) 674550',
    kepala_unit: 'Kepala Puskesmas Suranadi',
    status: 'Aktif',
  },
  {
    id: 'unit-011',
    kode_unit: 'PKM-10',
    nama_unit: 'Puskesmas Penimbung',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Penimbung, Gunungsari',
    telepon: '(0370) 675001',
    kepala_unit: 'Kepala Puskesmas Penimbung',
    status: 'Aktif',
  },
  {
    id: 'unit-012',
    kode_unit: 'PKM-11',
    nama_unit: 'Puskesmas Lembar',
    kategori: 'Puskesmas',
    alamat: 'Jl. Pelabuhan Lembar, Kec. Lembar',
    telepon: '(0370) 681900',
    kepala_unit: 'Kepala Puskesmas Lembar',
    status: 'Aktif',
  },
  {
    id: 'unit-013',
    kode_unit: 'PKM-12',
    nama_unit: 'Puskesmas Eyat Mayang',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Eyat Mayang, Lembar',
    telepon: '(0370) 681912',
    kepala_unit: 'Kepala Puskesmas Eyat Mayang',
    status: 'Aktif',
  },
  {
    id: 'unit-014',
    kode_unit: 'PKM-13',
    nama_unit: 'Puskesmas Jembatan Kembar',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Lembar, Jembatan Kembar',
    telepon: '(0370) 681925',
    kepala_unit: 'Kepala Puskesmas Jembatan Kembar',
    status: 'Aktif',
  },
  {
    id: 'unit-015',
    kode_unit: 'PKM-14',
    nama_unit: 'Puskesmas Kuripan',
    kategori: 'Puskesmas',
    alamat: 'Jl. TGH. Lalu Panji, Kuripan',
    telepon: '(0370) 684110',
    kepala_unit: 'Kepala Puskesmas Kuripan',
    status: 'Aktif',
  },
  {
    id: 'unit-016',
    kode_unit: 'PKM-15',
    nama_unit: 'Puskesmas Sigerongan',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Sigerongan, Lingsar',
    telepon: '(0370) 672440',
    kepala_unit: 'Kepala Puskesmas Sigerongan',
    status: 'Aktif',
  },
  {
    id: 'unit-017',
    kode_unit: 'PKM-16',
    nama_unit: 'Puskesmas Pelangan',
    kategori: 'Puskesmas',
    alamat: 'Jl. Pariwisata Pelangan, Sekotong',
    telepon: '(0370) 683990',
    kepala_unit: 'Kepala Puskesmas Pelangan',
    status: 'Aktif',
  },
  {
    id: 'unit-018',
    kode_unit: 'PKM-17',
    nama_unit: 'Puskesmas Sedau',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Sedau, Narmada',
    telepon: '(0370) 674992',
    kepala_unit: 'Kepala Puskesmas Sedau',
    status: 'Aktif',
  },
  {
    id: 'unit-019',
    kode_unit: 'PKM-18',
    nama_unit: 'Puskesmas Banyumulek',
    kategori: 'Puskesmas',
    alamat: 'Jl. Wisata Banyumulek, Kediri',
    telepon: '(0370) 671550',
    kepala_unit: 'Kepala Puskesmas Banyumulek',
    status: 'Aktif',
  },
  {
    id: 'unit-020',
    kode_unit: 'PKM-19',
    nama_unit: 'Puskesmas Parampuan',
    kategori: 'Puskesmas',
    alamat: 'Jl. Raya Labuapi, Parampuan',
    telepon: '(0370) 672901',
    kepala_unit: 'Kepala Puskesmas Parampuan',
    status: 'Aktif',
  },
  {
    id: 'unit-021',
    kode_unit: 'RSUD-01',
    nama_unit: 'RSUD Tripat Gerung',
    kategori: 'Rumah Sakit',
    alamat: 'Jl. H. Lalang Seta, Gerung Utara',
    telepon: '(0370) 681122',
    kepala_unit: 'Direktur RSUD Tripat',
    status: 'Aktif',
  },
  {
    id: 'unit-022',
    kode_unit: 'RSUD-02',
    nama_unit: 'RSUD Awet Muda Narmada',
    kategori: 'Rumah Sakit',
    alamat: 'Jl. Ahmad Yani No. 1, Narmada',
    telepon: '(0370) 671800',
    kepala_unit: 'Direktur RSUD Awet Muda',
    status: 'Aktif',
  },
  {
    id: 'unit-023',
    kode_unit: 'LAB-01',
    nama_unit: 'Labkesda Lombok Barat',
    kategori: 'Lab / UPTD',
    alamat: 'Jl. Pendidikan No. 5, Gerung',
    telepon: '(0370) 682990',
    kepala_unit: 'Kepala Labkesda',
    status: 'Aktif',
  },
  {
    id: 'unit-024',
    kode_unit: 'KB-01',
    nama_unit: 'Balai Penyuluhan KB Kec. Gerung',
    kategori: 'KB / PPKB',
    alamat: 'Jl. Gatot Subroto, Gerung',
    telepon: '(0370) 682500',
    kepala_unit: 'Koordinator KB Gerung',
    status: 'Aktif',
  },
  {
    id: 'unit-025',
    kode_unit: 'KB-02',
    nama_unit: 'Balai Penyuluhan KB Kec. Narmada',
    kategori: 'KB / PPKB',
    alamat: 'Jl. Raya Narmada, Narmada',
    telepon: '(0370) 671400',
    kepala_unit: 'Koordinator KB Narmada',
    status: 'Aktif',
  },
  {
    id: 'unit-026',
    kode_unit: 'KB-03',
    nama_unit: 'Balai Penyuluhan KB Kec. Gunungsari',
    kategori: 'KB / PPKB',
    alamat: 'Jl. Pariwisata Gunungsari',
    telepon: '(0370) 673100',
    kepala_unit: 'Koordinator KB Gunungsari',
    status: 'Aktif',
  },
];

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'usr-001',
    username: 'admin.dinkes',
    nama_lengkap: 'Administrator DINKES-PPKB (Admin Utama)',
    email: 'admin.dikes@lombokbaratkab.go.id',
    role: 'Admin Dinkes',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    nip: '198001012005011001',
    password: 'admin',
    no_hp: '081234567890',
    status: 'Aktif',
    terakhir_login: '2026-08-24 08:30',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-002',
    username: 'admin.gerung',
    nama_lengkap: 'Admin Puskesmas Gerung',
    email: 'admin.gerung@pkm.go.id',
    role: 'Admin Unit Kerja',
    unit_kerja: 'Puskesmas Gerung',
    nip: '198503142010011008',
    password: 'admin',
    no_hp: '081987654321',
    status: 'Aktif',
    terakhir_login: '2026-08-24 08:00',
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'usr-003',
    username: 'admin.narmada',
    nama_lengkap: 'Admin Puskesmas Narmada',
    email: 'admin.narmada@pkm.go.id',
    role: 'Admin Unit Kerja',
    unit_kerja: 'Puskesmas Narmada',
    nip: '198807222014022003',
    password: 'admin',
    no_hp: '081765432109',
    status: 'Aktif',
    terakhir_login: '2026-08-24 08:15',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'usr-004',
    username: 'admin.tripat',
    nama_lengkap: 'Admin RSUD Tripat Gerung',
    email: 'admin.tripat@rsud.go.id',
    role: 'Admin Unit Kerja',
    unit_kerja: 'RSUD Tripat Gerung',
    nip: '198205102008011005',
    password: 'admin',
    no_hp: '085234567891',
    status: 'Aktif',
    terakhir_login: '2026-08-24 07:45',
    created_at: '2026-01-12T00:00:00Z',
  },
];

export const INITIAL_APLIKASI_KEPEGAWAIAN: AplikasiKepegawaian[] = [
  {
    id: 'app-001',
    nama_aplikasi: 'SIASN BKN',
    kategori: 'Nasional (BKN / Kemenkes)',
    url_aplikasi: 'https://siasn.bkn.go.id',
    deskripsi: 'Sistem Informasi Aparatur Sipil Negara BKN untuk Kenaikan Pangkat, Mutasi, Pertek, Pensiun & Layanan ASN Nasional.',
    username: 'admin.dinkes.lobar',
    password: 'PasswordBKN2026!',
    custom_logo_url: '',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    status: 'Aktif',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'app-002',
    nama_aplikasi: 'E-Kinerja BKN',
    kategori: 'Nasional (BKN / Kemenkes)',
    url_aplikasi: 'https://kinerja.bkn.go.id',
    deskripsi: 'Pengelolaan Sasaran Kinerja Pegawai (SKP), Evaluasi Kinerja Periodik & Tahunan ASN sesuai PermenPAN-RB No 6/2022.',
    username: 'admin.dinkes.lobar',
    password: 'PasswordEkinerja2026!',
    custom_logo_url: '',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    status: 'Aktif',
    created_at: '2026-01-02T00:00:00.000Z',
  },
  {
    id: 'app-003',
    nama_aplikasi: 'MyASN BKN',
    kategori: 'Nasional (BKN / Kemenkes)',
    url_aplikasi: 'https://myasn.bkn.go.id',
    deskripsi: 'Portal Layanan Mandiri ASN Nasional untuk pemutakhiran data mandiri, riwayat profil, dokumen KTP/KK, dan sertifikat kompetensi.',
    username: '198503142010011008',
    password: 'PasswordMyASN2026!',
    custom_logo_url: '',
    unit_kerja: 'Semua Unit',
    status: 'Aktif',
    created_at: '2026-01-03T00:00:00.000Z',
  },
  {
    id: 'app-004',
    nama_aplikasi: 'SIMPEG Kab. Lombok Barat',
    kategori: 'Pemerintah Daerah (Lombok Barat / NTB)',
    url_aplikasi: 'https://simpeg.lombokbaratkab.go.id',
    deskripsi: 'Sistem Informasi Manajemen Kepegawaian BKD-PSDM Pemerintah Daerah Kabupaten Lombok Barat.',
    username: 'admin_dikes_lobar',
    password: 'SimpegLobar2026#',
    custom_logo_url: '/logo-lombok-barat.jpeg',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    status: 'Aktif',
    created_at: '2026-01-04T00:00:00.000Z',
  },
  {
    id: 'app-005',
    nama_aplikasi: 'SISDMK Kemenkes RI',
    kategori: 'Nasional (BKN / Kemenkes)',
    url_aplikasi: 'https://sisdmk.kemkes.go.id',
    deskripsi: 'Sistem Informasi Sumber Daya Manusia Kesehatan Kementerian Kesehatan RI untuk pemetaan nakes & tenaga non-kesehatan.',
    username: 'admin_sisdmk_lobar',
    password: 'SisdmkKemkes2026$',
    custom_logo_url: '',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    status: 'Aktif',
    created_at: '2026-01-05T00:00:00.000Z',
  },
  {
    id: 'app-006',
    nama_aplikasi: 'Plataran Sehat Kemenkes (LMS)',
    kategori: 'Nasional (BKN / Kemenkes)',
    url_aplikasi: 'https://lms.kemkes.go.id',
    deskripsi: 'Platform Pembelajaran dan Pelatihan Terpadu Kesehatan (Learning Management System) serta Satuan Kredit Profesi (SKP) Kemenkes.',
    username: 'admin.lms.dinkeslobar',
    password: 'PlataranSehat2026!',
    custom_logo_url: '',
    unit_kerja: 'Semua Unit',
    status: 'Aktif',
    created_at: '2026-01-06T00:00:00.000Z',
  },
  {
    id: 'app-007',
    nama_aplikasi: 'TASPEN One Stop Service (TOS)',
    kategori: 'Layanan Finansial & Jaminan ASN',
    url_aplikasi: 'https://tos.taspen.co.id',
    deskripsi: 'Portal Pelayanan Klim Otomatis Pensiun, Tabungan Hari Tua (THT), Jaminan Kecelakaan Kerja (JKK) & JKM PT TASPEN.',
    username: 'dinkes_lobar_taspen',
    password: 'TosTaspen2026@',
    custom_logo_url: '',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    status: 'Aktif',
    created_at: '2026-01-07T00:00:00.000Z',
  },
  {
    id: 'app-008',
    nama_aplikasi: 'BPJS Kesehatan e-DABU (PPU)',
    kategori: 'Layanan Finansial & Jaminan ASN',
    url_aplikasi: 'https://edabu.bpjs-kesehatan.go.id/Edabu',
    deskripsi: 'Elektronik Data Badan Usaha / Lembaga Pemerintah untuk mutasi kepesertaan jaminan kesehatan ASN, PPPK & Non-ASN.',
    username: 'edabu_dinkeslobar',
    password: 'BpjsEdabu2026#',
    custom_logo_url: '',
    unit_kerja: 'Dinas Kesehatan Kab. Lombok Barat',
    status: 'Aktif',
    created_at: '2026-01-08T00:00:00.000Z',
  },
];

